site_name: django-rest-framework-supertest
site_url: https://inventare.github.io/django-rest-framework-supertest
repo_url: https://github.com/inventare/django-rest-framework-supertest
repo_name: inventare/django-rest-framework-supertest

theme:
  name: material
  palette:
    scheme: slate
    primary: blue
  icon:
    repo: fontawesome/brands/github
    logo: material/image
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight

markdown_extensions:
  - tables
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - glightbox
  - awesome-pages
  - search

extra:
  homepage: https://inventare.github.io/django-rest-framework-supertest/

nav:
  - index.md
  - Philosophy:
    - ... | flat | philosophy/*.md
  - Architecture Decision Records:
    - ... | flat | adr/*.md
