[tool.ruff]
exclude = [
    ".eggs",
    ".git",
    ".git-rewrite",
    ".ruff_cache",
    ".github",
    ".venv",
    "__pypackages__",
    "venv",
    "scripts",
]
line-length = 88
indent-width = 4
target-version = "py38"

[tool.ruff.lint]
select = [
    # TODO: Pyflakes (F)

    # TODO: pycodestyle (E, W)

    # mccabe
    "C901",
    # isort
    "I001", "I002",
    # pep8-naming
    "N801", "N802", "N803", "N804", "N805", "N806", "N807", "N811", "N812", "N813",
    "N814", "N815", "N816", "N817", "N818", "N999",
    # pydocstyle
    "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107", "D200", "D201",
    "D202", "D204", "D205", "D206", "D207", "D208", "D209", "D210", "D211", "D213",
    "D214", "D300", "D400", "D401", "D402", "D403", "D404", "D405", "D410", "D411",
    "D412", "D414", "D415", "D416", "D417", "D418", "D419",
    # pyupgrade
    "UP001", "UP003", "UP004", "UP005", "UP008", "UP011", "UP012", "UP015", "UP018",
    "UP019", "UP020", "UP023", "UP024", "UP025", "UP026", "UP027", "UP028", "UP029",
    "UP030", "UP031", "UP032", "UP033", "UP034", "UP037", "UP039",
    # flake8-annotations
    "ANN001", "ANN002", "ANN003", "ANN201", "ANN202", "ANN205", "ANN206", "ANN401",
    # flake8-bandit
    "S101", "S102", "S104", "S105", "S106", "S107", "S701", "S608",
    # flake8-blind-except
    "BLE001",
    # flake8-boolean-trap
    "FBT001", "FBT002", "FBT003",
    # flake8-bugbear
    "B002", "B003", "B004", "B005", "B006", "B007", "B008", "B009", "B010", "B011",
    "B012", "B013", "B014", "B015", "B016", "B017", "B018", "B019", "B020", "B021",
    "B022", "B023", "B024", "B025", "B026", "B027", "B028", "B029", "B030", "B031",
    "B032", "B033", "B034", "B904", "B905",
    # flake8-builtins
    "A001", "A002", "A003",
    # flake8-commas
    "COM812", "COM818", "COM819",
    # flake8-comprehensions
    "C400", "C401", "C402", "C403", "C404", "C405", "C406", "C408", "C409", "C410",
    "C411", "C413", "C414", "C415", "C416", "C417", "C418", "C419",
    # flake8-django
    "DJ001", "DJ006", "DJ007", "DJ008", "DJ012",
    # flake8-errmsg
    "EM101", "EM102", "EM103",
    # flake8-import-conventions
    "ICN001", "ICN002", "ICN003",
    # flake8-no-pep420
    "INP001",
    # flake8-pie
    "PIE790", "PIE794", "PIE796", "PIE800", "PIE804", "PIE807", "PIE808", "PIE810",
    # flake8-print
    "T201", "T203",
    # flake8-raise
    "RSE102",
    # flake8-return
    "RET501", "RET502", "RET503", "RET504", "RET505", "RET506", "RET507", "RET508",
    # flake8-self
    "SLF001",
    # flake8-simplify
    "SIM102", "SIM103", "SIM105", "SIM107", "SIM109", "SIM110", "SIM112", "SIM114",
    "SIM115", "SIM116", "SIM117", "SIM118", "SIM201", "SIM202", "SIM208", "SIM210",
    "SIM211", "SIM212", "SIM220", "SIM221", "SIM222", "SIM223", "SIM300", "SIM401",
    "SIM910",
    # flake8-gettext
    "INT001", "INT002", "INT003",
    # flake8-unused-arguments
    "ARG001", "ARG002", "ARG003", "ARG004", "ARG005",
    # flake8-todos
    "TD001", "TD003", "TD004", "TD005", "TD007",
    # flake8-fixme
    "FIX001", "FIX003", "FIX004",
    # eradicate
    "ERA001",
    # TODO: Pylint (PL)

    # tryceratops
    "TRY002", "TRY003", "TRY004", "TRY200", "TRY201", "TRY300", "TRY301", "TRY400",
    "TRY401",
    # TODO: Perflint (PERF)

    # TODO: refurb (FURB)

    # TODO: flake8-logging

    # TODO: Ruff-specific rules (RUF)
    
]
ignore = []

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.pydocstyle]
convention = "google"
