name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Run Lint on Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: "."
          args: --preview
